/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Text,
  'description' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SiblingProfile = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'emoji' : IDL.Text,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSibling' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteSibling' : IDL.Func([IDL.Nat], [], []),
  'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
  'getMessage' : IDL.Func([IDL.Nat], [Message], ['query']),
  'getRecentMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getSiblingProfile' : IDL.Func([IDL.Nat], [SiblingProfile], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalActivities' : IDL.Nat,
          'totalMessages' : IDL.Nat,
          'totalSiblings' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'init' : IDL.Func([], [], []),
  'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'listSiblings' : IDL.Func([], [IDL.Vec(SiblingProfile)], ['query']),
  'postMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Text,
    'description' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SiblingProfile = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'emoji' : IDL.Text,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addSibling' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteSibling' : IDL.Func([IDL.Nat], [], []),
    'getActivity' : IDL.Func([IDL.Nat], [Activity], ['query']),
    'getMessage' : IDL.Func([IDL.Nat], [Message], ['query']),
    'getRecentMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getSiblingProfile' : IDL.Func([IDL.Nat], [SiblingProfile], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalActivities' : IDL.Nat,
            'totalMessages' : IDL.Nat,
            'totalSiblings' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'init' : IDL.Func([], [], []),
    'listActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'listMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'listSiblings' : IDL.Func([], [IDL.Vec(SiblingProfile)], ['query']),
    'postMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };