/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'creator' : string,
  'description' : string,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface SiblingProfile {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'emoji' : string,
}
export interface _SERVICE {
  'addActivity' : ActorMethod<[string, string], bigint>,
  'addSibling' : ActorMethod<[string, string, string], bigint>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'deleteSibling' : ActorMethod<[bigint], undefined>,
  'getActivity' : ActorMethod<[bigint], Activity>,
  'getMessage' : ActorMethod<[bigint], Message>,
  'getRecentMessages' : ActorMethod<[bigint], Array<Message>>,
  'getSiblingProfile' : ActorMethod<[bigint], SiblingProfile>,
  'getStats' : ActorMethod<
    [],
    {
      'totalActivities' : bigint,
      'totalMessages' : bigint,
      'totalSiblings' : bigint,
    }
  >,
  'init' : ActorMethod<[], undefined>,
  'listActivities' : ActorMethod<[], Array<Activity>>,
  'listMessages' : ActorMethod<[], Array<Message>>,
  'listSiblings' : ActorMethod<[], Array<SiblingProfile>>,
  'postMessage' : ActorMethod<[string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];